"""added matches

Revision ID: 2817df33d945
Revises: 9c527eb59309
Create Date: 2025-06-25 22:28:55.098298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2817df33d945'
down_revision: Union[str, None] = '9c527eb59309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_1_id', sa.BigInteger(), nullable=False),
    sa.Column('user_2_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1_id', 'user_2_id', name='_user_match_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_matches')
    # ### end Alembic commands ###
