"""Alter user_id to BIGINT

Revision ID: 4bd1327e7333
Revises: 682c643525af
Create Date: 2024-11-12 03:09:55.465434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd1327e7333'
down_revision: Union[str, None] = '682c643525af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('users', 'user_id', type_=sa.BigInteger)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
