"""Update tables

Revision ID: 9c527eb59309
Revises: 8023e6834d1e
Create Date: 2025-06-25 11:35:20.567881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c527eb59309'
down_revision: Union[str, None] = '8023e6834d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('was_liked',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('liked_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['liked_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'liked_user_id', name='_was_liked_uc')
    )
    op.drop_table('user_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_matches',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('matched_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.user_id'], name='user_matches_matched_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_matches_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_matches_pkey'),
    sa.UniqueConstraint('user_id', 'matched_user_id', name='_user_match_uc')
    )
    op.drop_table('was_liked')
    # ### end Alembic commands ###
